import Head from 'next/head'
import styles from '../styles/Home.module.sass'
import Header from '../components/js/header'
import Eyecatch from '../components/js/top/eyecatch'
import Profile from '../components/js/top/profile'
import Product from '../components/js/top/product'
import Footer from '../components/js/footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <Eyecatch />
        <Profile />
        <Product />
      </main>
      <Footer />
    </div>
  )
}
