import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.sass'
import Header from '../components/js/header'
import Footer from '../components/js/footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <p>メインコンテンツ</p>
      </main>
      <Footer />
    </div>
  )
}
